# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-securepv-test
  namespace: mapr-examples
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "mapr.com/maprfs"
    options:
      cluster: "mysecurecluster"
      cldbHosts: "cldb1 cldb2 cldb3"
      securityType: "secure"
      ticketSecretName: "mapr-ticket-secret"
      ticketSecretNamespace: "mapr-examples"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-securepv
  namespace: mapr-examples
spec:
  containers:
  - name: base
    imagePullPolicy: Always
    image: docker.artifactory/maprtech/simpleclient:1.00
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    command:
    - bash
    - -c
    - /start.sh
    volumeMounts:
    - mountPath: /mapr
      name: maprflex
  volumes:
    - name: maprflex
      persistentVolumeClaim:
        claimName: securemaprclaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: securemaprclaim
  namespace: mapr-examples
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
